### ISSUE TITLE
Tests fail & App not working on El Capitan / Xcode 7

### ISSUE THREAD

**Issue by ghost** [Daij-Djan/xsd2cocoa#6]
Hello, 

I was pretty glad to find a framework helping me in working with XSDs. Unfortunately, I can build the App and run, but the generation fails. I then started the tests, and many of them fail.
I noticed that several error message are talking of "namespace", so it may be that this relates to the other open issue here.
As I'm not using ObjC, but Swift, I'm pretty helpless in fixing anything myself... ;-)
I attached the test results for your information.

Best regards
- Hardy
  [TestResults.txt](https://github.com/Daij-Djan/xsd2cocoa/files/46302/TestResults.txt)

**Comment by Daij-Djan** [comment]
hi, 
weird. you are missing the default include directory.
im not on 10.11 and there all tests work :(

ill look into it - maybe tomorrow night maybe moday

can you provide me the xsd & xml you wanna parse?

cheers,
dominik

**Comment by ghost** [comment]
Hello Dominik,

thanks for your response! Actually, I’m not yet at the point to input any XSD (actually, I can, but then the app fails, probably for the same reason - that’s why I executed the tests - so the effect is independent of any data). 

Attached you find a screenshot of the test run. Perhaps this gives you some more hints.

Cheerio,
Hardy

> Am 28.11.2015 um 16:33 schrieb Dominik Pich notifications@github.com:
> 
> hi, 
> weird. you are missing the default include directory.
> im not on 10.11 and there all tests work :(
> 
> ill look into it - maybe tomorrow night maybe moday
> 
> can you provide me the xsd & xml you wanna parse?
> 
> cheers,
> dominik
>

**Comment by Daij-Djan** [comment]
ok I fixed the unit tests for 10.11. the problem was that I used the /usr/include dir directly and on 10.11 this isn't there by default. They should be all green now. 

The demo apps also work fine for me. 

what is your issue exactly?

**Comment by ghost** [comment]
Great, things look much better now. However, there is still a problem in some of the Swift tests:
![bildschirmfoto 2015-12-06 um 11 48 25](https://cloud.githubusercontent.com/assets/9914806/11612952/75e49d70-9c0f-11e5-8378-76cdd2124ee8.png)
This concerns three of those tests, all other tests are working fine:
![bildschirmfoto 2015-12-06 um 11 50 10](https://cloud.githubusercontent.com/assets/9914806/11612954/95be09b0-9c0f-11e5-8ba4-bea103ea5df9.png)

**Comment by ghost** [comment]
I tried to run the tool with my own XSD. I selected the XSD file, the output folder was elicited automatically, target was "Swift", pushing "Process" button => nothing happens. No error, no change of the output folder, no dialog, just nothing... strange...

**Comment by ghost** [comment]
I noticed, btw, that when after the <?xml...?> line a comment line occurs (like with Altova XMLSpy), the input XSD file is not recognized as such by the tool.

**Comment by ghost** [comment]
Changing to "ObjC" does not change the bevaviour of doing nothing.

**Comment by ghost** [comment]
I removed all whitespaces and comments from my XSD file, but no change. (I suspected the comments to be the reason for the problems.)

**Comment by Daij-Djan** [comment]
I made the parsers way more tolerant concerning other content atop the root element

**Comment by Daij-Djan** [comment]
ill upload a version tonight (CET)
